export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPLOAD_EXCEL_FILE_BEGIN = "UPLOAD_EXCEL_FILE_BEGIN";
export const UPLOAD_EXCEL_FILE_SUCCESS = "UPLOAD_EXCEL_FILE_SUCCESS";
export const UPLOAD_EXCEL_FILE_ERROR = "UPLOAD_EXCEL_FILE_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
